server:
  port: 8002

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:mysql://localhost:3306/recruit_system?useSSL=false&serverTimezone=UTC
    username: root
    password: @Aa720404
    jpa:
      open-in-view: false
      show-sql: false
      hibernate:
        ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.companyservice.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??SQL?????
