server:
  port: 8003

spring:
  application:
    name: jobseeker-service
  datasource:
    url: jdbc:mysql://localhost:3306/recruit_system?useSSL=false&serverTimezone=UTC
    username: root
    password: '@Aa720404'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
