server:
  port: 8001

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/recruit_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: @Aa720404
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
